task4/classmates/urls.py
from django.urls import path
from . import views

app_name = 'classmates'

urlpatterns = [
    path('', views.index, name='home'),
    path('addbro', views.addBro,name='addbro'),
    path('addsis', views.addSis,name='addsis')
]

task4/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views


urlpatterns = [
    path('', include('classmates.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]

task4/classmates/models.py
from django.db import models


class Message(models.Model):
    title = models.CharField(default='', max_length=150)
    username = models.CharField(default='', max_length=150)
    date = models.DateTimeField(auto_now=True)
    bro = models.BigIntegerField(default=0)
    sis = models.BigIntegerField(default=0)

    def __str__(self) -> str:
        return  f'{self.bro} Bro {self.sis} Sis'

task4/classmates/views.py
from django.core.checks import messages
from django.shortcuts import redirect, render
from .models import Message
from django.contrib.auth.decorators import login_required


def index(request):
    message, create = Message.objects.get_or_create()
    return render(request, 'classmates/home.html',{'message':message})

@login_required(login_url='/')
def addBro(request):
    add(request, True)
    return redirect('classmates:home')

@login_required(login_url='/')
def addSis(request):
    add(request, False)
    return redirect('classmates:home')

def add(request, brosis):
    message = Message.objects.first()
    message.title = 'Bro!' if brosis else 'Sis!'
    message.username = request.user.username
    if brosis: message.bro += 1
    else: message.sis += 1
    message.save()

task4/classmates/templates/classmates/base_layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Classmates</title>
  </head>
  <style>  
  body {
    background-color: #0088cc;    
        }
  .navbar-nav {
            margin-left: auto;
        }
   a { 
    text-decoration: none;
    color:darkslategray;
   } 
  </style>
  <body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      {% block content %} {% endblock content %}
    </nav>
    <div class="d-flex justify-content-center"><h1><br><br><br><br><br></h1></p></div>
      {% block logic%}
      {% endblock logic %}
    
  </body>
</html>

task4/classmates/templates/classmates/home.html
{% extends 'classmates/base_layout.html' %} {% load socialaccount %}

{% block content %}

    {% if user.is_authenticated %}
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="btn btn-dark">Hello, {{user.username}}</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'account_logout' %}" class="btn btn-dark">Logout</a>
        </li>
      </ul>
    {% else %}     
      <ul class="navbar-nav">
        <li class="nav-item">
          <a  class="btn btn-dark">Login with</a>
            </a>
        </li>
        <li class="nav-item">
          <a href="{% provider_login_url 'google' %}" class="btn btn-primary"><i class="fa fa-google fa-fw"></i> </a>  
          .
            </a>
        </li>
        <li class="nav-item">
          <a href="{% provider_login_url 'github' %}" class="btn btn-secondary"><i class="fa fa-github fa-fw"></i></a>
          .
            </a>
        </li>
        <li class="nav-item">
          <a href="{% provider_login_url 'vk' %}" class="btn btn-primary"><i class="fa fa-vk fa-fw"></i></a>  
          .
            </a>
        </li>
    </ul>    
    {% endif %}

{% endblock content %}

{% block logic%}

  {%if user.is_authenticated%}
  <div class="d-flex justify-content-center">
      <a href="{% url 'classmates:home'%}"><small>{{message.title}}<br>Send by {{message.username}} at {{message.date|date:"h:i"}}</small></a>
  </div>
  <div class="d-flex justify-content-center">
      <a href="{% url 'classmates:addbro'%}" class="btn btn-dark "><h1>Bro!</h1></a>
      <p><font color="0088cc">...</font></p>
      <a href="{% url 'classmates:addsis'%}" class="btn btn-dark"><h1>Sis!</h1></a>
  </div>      
  {%else%}
  <div class="d-flex justify-content-center">
    <h1>{{message.bro}} Bro! {{message.sis}} Sis!</h1>
  </div>
  {%endif%}

{% endblock logic %}