course work/kinovik/kinovik/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls), 
    path('i18n/', include('django.conf.urls.i18n')),
    
]

urlpatterns += i18n_patterns(
    path('accounts/',include('allauth.urls')),
    path('', include('revapp.urls')),
)

course work/kinovik/revapp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'revapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.searchArticle, name='search'),
    path('group/', views.groupArticle, name='group'),
    path('create/', views.createArticle, name='create'),
    path('rate-article/', views.rateArticle, name='ratearticle'),
    path('my-articles/', views.myArticles, name='myarticles'),
    path('tag/<slug:slug>/', views.tagged, name='tagged'),
    path('<slug:slug>/like', views.likeUnlikeArticle, name='likeunlike'),
    path('<slug:slug>/detail', views.detailArticle, name='detail'),
    path('<slug:slug>/album', views.otherImages, name='otherimages'),
    path('<slug:slug>/update', views.updateArticle, name="update"),
    path('<slug:slug>/delete', views.deleteArticle, name='delete'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course work/kinovik/revapp/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.contrib.auth.models import User
from django.db.models.base import Model
from taggit.managers import TaggableManager
from django.template.defaultfilters import slugify as d_slug
from cloudinary.models import CloudinaryField
from ckeditor.fields import RichTextField

alphabet = {'а': 'a', 'б': 'b', 'в': 'v', 'г': 'g', 'д': 'd', 'е': 'e', 'ё': 'yo', 'ж': 'zh', 'з': 'z', 'и': 'i',
            'й': 'j', 'к': 'k', 'л': 'l', 'м': 'm', 'н': 'n', 'о': 'o', 'п': 'p', 'р': 'r', 'с': 's', 'т': 't',
            'у': 'u', 'ф': 'f', 'х': 'kh', 'ц': 'ts', 'ч': 'ch', 'ш': 'sh', 'щ': 'shch', 'ы': 'i', 'э': 'e', 'ю': 'yu',
            'я': 'ya'}

def slugify(s):
    return d_slug(''.join(alphabet.get(w, w) for w in s.lower()))


class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

    def __str__(self):
        return str(self.user.username)
    
    def get_likes_given(self):
        likes = self.likes.all()
        totalLikes = 0
        for item in likes:
            if item.value == "Like":
                totalLikes += 1
        return totalLikes

    def get_likes_recieved(self):
        articles = self.articles.all()
        total =  0
        for item in articles:
            total += item.fans.all().count()
        return total 


class Article(models.Model):
    GROUP = [
        ('Movie', 'Movie'),
        ('Games', 'Games'),
        ('Books', 'Books')
    ]
    SCALE =[(1,1), (2,2), (3,3), (4,4), (5,5), (6,6), (7,7), (8,8), (9,9), (10,10)]
    title = models.CharField(max_length=200, unique=True, null=True)
    slug = models.SlugField(null=True, blank=True)
    group = models.CharField(max_length=100, choices=GROUP, null = True)
    body = RichTextField(blank = True)   
    tags = TaggableManager()
    date_created = models.DateTimeField(auto_now_add=True,null=True)
    date_updated = models.DateTimeField(auto_now=True,null=True)
    fans = models.ManyToManyField(Account, related_name='liked', blank=True)
    rating = models.IntegerField(default=-1, choices=SCALE)
    author = models.ForeignKey(Account, on_delete=models.CASCADE, default=None, related_name='articles')

    class Meta:
        ordering = ['-date_created']    

    def __str__(self):
        return self.title
    
    def snippet(self):
        if self.body != '':
            return f'{self.body[:30]}...'
        else:
            return '[]'    
    
    def numLikes(self):
        return self.fans.all().count()

    def numViews(self):
        return self.views.all().count()

    def numComments(self):
        return self.comments.all().count()

    def numRat(self):
        return self.stars.all().count()
    
    def calculateRating(self):
        stars = self.stars.all()
        numStars = self.numRat()
        average = [x.score/numStars for x in stars]
        sum = 0
        for el in average: sum += el
        return sum

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Article, self).save(*args, **kwargs)


class Views(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='views')
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='views')

    def __str__(self):
        return f'{self.article.title}-{self.user.user.username}'
    


class Comment(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='comments')
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    body = models.TextField(max_length=300)
    date_created = models.DateTimeField(auto_now_add=True,null=True)
    date_updated = models.DateTimeField(auto_now=True,null=True)

    class Meta:
        ordering = ['-date_created']

    def __str__(self):
        return str(self.pk)
    

class Like(models.Model):
    LIKE_CHOICES = [
        ('Like','Like'),
        ('Unlike', 'Unlike'),
    ]
    
    user =models.ForeignKey(Account, on_delete=models.CASCADE, related_name='likes')
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='likes')
    value =  models.CharField(choices=LIKE_CHOICES, max_length=10)
    date_created = models.DateTimeField(auto_now_add=True,null=True)
    date_updated = models.DateTimeField(auto_now=True,null=True)

    def __str__ (self):
        return f"{self.user}-{self.article}-{self.value}"



class Photo(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='images')
    image = CloudinaryField('image')


class Rating(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='stars')
    user = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='stars')
    score = models.IntegerField(default=0,
        validators=[
            MaxValueValidator(5),
            MinValueValidator(0)
        ])

    def __str__(self):
        return f'{self.article.title}-{self.user.user.username}-{self.score}'
    

course work/kinovik/revapp/forms.py
from django import forms
from . import models
from . models import Comment, Photo



class ArticleForm(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body','group','tags','rating']

    def is_valid(self) -> bool:
        valid = super().is_valid()
        if not valid:
            return valid
        if '-' in self.cleaned_data['title']:
            return False
        else: return True



class UpdateForm(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body','group', 'rating']
    

class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ['image']


class CommentForm(forms.ModelForm):
    body = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder':'Add a comment...'}))
    class Meta:
        model = Comment
        fields = ['body']

course work/kinovik/revapp/views.py
from django.db import connection
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.db.models.sql.query import RawQuery
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .filters import ArticleFilter
from .models import Article, Account, Comment, Photo, Like, Rating, Views
from taggit.models import Tag
from django.http import JsonResponse
from . import forms


def index(request):  
    checkAccount(request)
    articles = Article.objects.all()
    articles = sorted(articles, key=lambda x: x.numLikes(), reverse=True)
    tags = Tag.objects.all()
    articles = paginate(request, articles, modelPerPage=6)
    return render(request, 'revapp/article_list.html',{'articles':articles,'tags':tags})

@login_required(login_url='/accounts/login')
def myArticles(request):
    account = Account.objects.select_related('user').filter(user=request.user).get()
    if account :
        myFilter = ArticleFilter(request.GET,queryset=Article.objects.filter(author = account))
        articles = myFilter.qs
    else:
        Account.objects.create(user=request.user)
    return render(request, 'revapp/my_article.html', {'articles':articles, 'filter':myFilter})

def detailArticle(request,slug):
    article = Article.objects.filter(slug=slug).get()
    print(article.calculateRating())
    if request.method =='POST':
        c_form = forms.CommentForm(request.POST)
        if c_form.is_valid():
            comment = c_form.save(commit=False)
            comment.user = Account.objects.filter(user = request.user).get()
            comment.article = article
            comment.save()
            c_form = forms.CommentForm()
    else:
        c_form = forms.CommentForm()
    if request.user.is_authenticated:
        account = Account.objects.get(user=request.user)
        views, created = Views.objects.get_or_create(user=account, article_id=article.id)
        if created:
            views.save()  
    else:
        account={}
    return render(request, 'revapp/article_detail.html', {'article':article,'account':account,'c_form':c_form})

login_required(login_url='/accounts/login')
def rateArticle(request):
    if request.method=='POST':
        el_id = request.POST.get('el_id')
        val = request.POST.get('val')
        article = Article.objects.get(id=el_id)
        account = Account.objects.get(user = request.user)
        rat, created=Rating.objects.get_or_create(article=article, user = account)
        rat.score = val
        rat.save()
        return JsonResponse({'success':'true', 'score':val}, safe=False)
    return JsonResponse({'success':'false'})

@login_required(login_url='/accounts/login')
def createArticle(request):
    if request.method=='POST':
        images =  request.FILES.getlist('images')
        form = forms.ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.author = Account.objects.filter(user_id=request.user.id).first()
            article.save()
            addImages(article,images)
            form.save_m2m()
            return redirect('revapp:myarticles')
    else:
        form = forms.ArticleForm()
    return render(request, 'revapp/article_create.html',{'form':form})

@login_required(login_url='/accounts/login')
def updateArticle(request, slug):
    if request.user != Article.objects.filter(slug=slug).first().author.user:
        return redirect('revapp:index')
    article = Article.objects.filter(slug=slug).get()
    form = forms.UpdateForm(request.POST, instance=article)
    if request.method == 'POST':
        if form.is_valid():
            article = form.save(commit=False)
            article.save()
            form.save_m2m()
            return redirect('revapp:myarticles')      
    else:
         form = forms.ArticleForm(instance=article)
    return render(request,  'revapp/article_update.html', {'form':form, 'article':article})

def otherImages(request, slug):
    photoObj = Article.objects.filter(slug=slug).get().images.all()
    images = []
    for obj in photoObj:
        images.append(obj.image)
    return render (request, 'revapp/article_album.html', {'images':images,'slug':slug})

@login_required(login_url='/accounts/login')
def deleteArticle(request,slug):
    if request.user != Article.objects.filter(slug=slug).first().author.user:
        return redirect('revapp:index')
    article = Article.objects.filter(slug=slug).get()
    article.tags.remove()
    article.delete()
    remove_all_tags_without_objects()
    return redirect ('revapp:myarticles')

@login_required(login_url='/accounts/login')
def likeUnlikeArticle(request, slug):
    if request.method =='POST':
        article = Article.objects.filter(slug=slug).get()
        account = Account.objects.filter(user=request.user).get()
        article_id = request.POST.get('article_id')
        if account in article.fans.all():
            article.fans.remove(account)
        else:
            article.fans.add(account)
        like, created = Like.objects.get_or_create(user=account, article_id=article_id)
        if not created:
            like.value = 'Unlike' if like.value=='Like' else 'Like'
        else:
            like.value='Like'
        like.save()
        article.save()
    return redirect('revapp:detail', slug =slug)

def searchArticle(request):
    query =  request.GET.get('q')
    articles = set()
    if query:     
        articles.update(Article.objects.filter(Q(title__icontains=query)| Q(body__icontains=query)))    
        print(articles)
        comments = Comment.objects.filter(Q(body__icontains=query))
        artcomm = [comment.article for comment in comments]
        articles.update(artcomm)

    return render(request, 'revapp/article_list.html', {'articles':articles})

def groupArticle(request):
    group = request.GET['group']
    articles = []
    for item in Article.GROUP:
        if group in item:
            articles = Article.objects.filter(group=group).all()
            return render( request, 'revapp/article_list.html', {'articles': articles})
    return redirect('revapp:index')
    
def tagged(request,slug):
    tag = get_object_or_404(Tag, slug=slug)
    articles =  Article.objects.filter(tags=tag)
    return render(request, 'revapp/article_list.html', {'articles':articles,'tag':tag})

def paginate(request, someModel, modelPerPage=6):
    page = request.GET.get('page',1)    
    paginator = Paginator(someModel, modelPerPage)
    try:
        someModel = paginator.page(page)
    except PageNotAnInteger:
        someModel = paginator.page(1)
    except EmptyPage:
        someModel = paginator.page(paginator.num_pages)
    return someModel

def checkAccount(request):
    if request.user.is_authenticated:
        account,created = Account.objects.get_or_create(user=request.user)

def addImages(article,images):
    for image in images:
        Photo.objects.create(image=image, article =article)

def remove_all_tags_without_objects():
    for tag in Tag.objects.all():
        if tag.taggit_taggeditem_items.count() == 0:
            tag.delete()

course work/kinovik/revapp/templates/revapp/article_album.html
{%extends 'home.html'%}
{%load i18n%}


{%block content%}


    <div class="container">
        <h1>{%trans 'Album'%}</h1>
        <div class="container">
          <div class="card-columns">
            {%for image in images%}
            <div class="card">

                   <img class="card-img-top" src="{{image.url}}"> 


            </div>  
            {%endfor%}    
            
        </div> 
        <div class="mt-5">
        <a href="{%url 'revapp:detail' slug%}"><span style="color:#17a2b8"> <i class="fas fa-arrow-alt-circle-left fa-4x"></i></span></a>
    </div>
{%endblock%}

course work/kinovik/revapp/templates/revapp/article_create.html
{%extends 'home.html'%}
{% load crispy_forms_tags%}
{% load static%}
{% load i18n%}
{%block content%}

<div class="container w-50  ">
    <font color="white">
    <form action="{%url 'revapp:create'%}" method="POST" enctype="multipart/form-data">
        {%csrf_token%}
        {{form.media}}  
        <div class="form-row">
            <div class="form-group col-md-6 mb-0">
              {{ form.title|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 mb-0">
              {{ form.group|as_crispy_field }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6 mb-0">

              {{ form.body|as_crispy_field }}
            </div>  
        </div>
        <div class="form-row">
            <div class="form-group  col-md-6 mb-0 ">
              {{form.rating|as_crispy_field}}
            </div>
            <div class="form-group col-md-6 mb-0">
              <div class="form-group  mb-0">
                <label>{% trans 'Tags'%}</label>
                <input type="text" data-role="tagsinput" class="form-control" name="tags">         
              </div>
            </div>
        </div>
           
        <div class="form-row">
        <div class="form-group  col-md-6 mb-2 mb-0">
                  <label>{% trans 'Upload Image'%}</label>
                  <input required name="images" type="file" multiple class="form-control-file">
                </div>           
              </div>
              <button class="btn btn-success btn-block " type="submit">{% trans 'ADD ARICLE'%}<i class="fas fa-plus"></i></button>
        </div>   

</font>
</div>
{%endblock%}

{%block extra_body%}
<script src="{%static 'ckeditor/ckeditor-init.js'%}"></script>
<script src="{%static 'ckeditor/ckeditor/ckeditor.js'%}"></script>
{%endblock%}

course work/kinovik/revapp/templates/revapp/article_detail.html
{% extends 'home.html' %}
{% load cloudinary  %}
{% load static%}
{% load crispy_forms_tags%}
{% load i18n%}
{% block content %}

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">

<style>body{background-color:#4D4C7D;}</style>

<div class="d-flex justify-content-center">
    <div class="col-md-10">
        <h1>{{article.title}}</h1>
        <div class="card">
            <a href ="{%url 'revapp:otherimages' article.slug%}"> <img class="card-img-top" src="{{article.images.first.image.url}}"> </a>
                <div class="card-body">
                        {%if user.is_authenticated%}
                        <form class="rate-form" action="" method="POST" id={{article.id}}>
                            {%csrf_token%}
                            <button type="submit" class="fa fa-star btn-star" id="first"></button>
                            <button type="submit" class="fa fa-star btn-star" id="second"></button>
                            <button type="submit" class="fa fa-star btn-star" id="third"></button>
                            <button type="submit" class="fa fa-star btn-star" id="fourth"></button>
                            <button type="submit" class="fa fa-star btn-star" id="fifth"></button>
                        </form>
                        <div id="confirm-box"></div>
                        {%endif%}
                        <p class="card-text text-right mb-0 ">  
                            <small class="text-muted">
                                {% for tag in article.tags.all %}
                                <a href="{% url 'revapp:tagged' tag.slug %}" class="mr-1 badge badge-info">#{{ tag }}</a>
                                {% endfor %}
                                <i class="fas fa-eye">      {{article.numViews}}</i><i class="comment icon"></i>
                                {{ article.numComments }} <i class="far fa-user">  {{article.author.user.username}}</i>  <i class="fas fa-calendar-alt">   {{article.date_created|date:"M d, Y"}}</i>
                                {%if account.user.is_authenticated%}
                                <form action="{%url 'revapp:likeunlike' article.slug%}" method="POST" class="like-form" id="{{article.id}}">
                                    {%csrf_token%}
                                <input type="hidden" name='article_id' value="{{article.id}}" id="like">
                                <button type="submit"  class="btn btn-sm  like-btn{{article.id}}">
                                    {%if account not in article.fans.all%}
                                    <span style="color: #6c757d;"><i class="fas fa-thumbs-up">Like</i></span>
                                    {% else %}
                                    <span style="color:rgb(176, 66, 220) ;"><i class="fas fa-thumbs-up">Unlike</i></span>
                                    {%endif%}                            
                                </button>    
                                 </form>
                                <p class="like-count{{article.id}}">{{article.numLikes}}</p>
                                {%endif%}                
                                  
                            </small>
                        </p>
                        <p class="card-text text-left">{{article.body|safe}}</p>
                        <h3 class="card-text text-rigt">{{article.rating}}/10</3>

                </div>
            </a>
        </div>
        {% if account.user.is_authenticated%}
        <div class="extra content">
            <div class="mb-5">              
            </div>
            <button class="cmt_btn ui button mb-5"> {% trans 'comments'%}</button>
            <div class="comment-box">
                
            {% if article.comments.all %}
                {% for c in article.comments.all %}                
                    <div class="ui segment mb-5">                        
                        <div class='mt-5 text-left' >{{ c.body }}</div>
                        <p class="card-text text-right mt-0">
                           <small class="text-muted"><i class="fas fa-feather"></i>{{ c.user }} <i class="fas fa-calendar-alt">   {{c.date_created|date:"d M H:i"}}</i></span></small>
                           </p>
                    </div>                
                {% endfor %}
               
            {% endif %}
            <form action="" method="POST"class='ui fluid form'>
                {% csrf_token %}
                <input type="hidden" name="article_id" value={{article.id}}>
                {{ c_form }}
                <button type="submit" name="submit_c_form" class="ui secondary button mt-5 w-full"><span style="color:purple"><i class="fab fa-telegram fa-2x"></i></span></button>
            </form>
            </div>
        </div>
        {%endif%}
    </div>        
</div> 

{% endblock content %}

{%block extra_body%}
<script src="{% static 'js/likeunlike.js'%}"></script>
<script src="{% static 'js/hide.js'%}"></script>
<script src="{% static 'js/stars.js'%}"></script>
{%endblock extra_body%}

course work/kinovik/revapp/templates/revapp/article_list.html
{%extends 'home.html'%}
{% load cloudinary%}
{% load i18n%}
{%block content%}
<div class="container">
  <div class="container">
    <div class="card-columns">
      {%for article in articles%}
      <div class="card">
          <a href="{%url 'revapp:detail' article.slug%}">
             <img class="card-img-top" src="{{article.images.first.image.url}}"> 
 
              <div class="card-body">
                  <h5 class="card-title">{{article.title}}</h5>
                  <p class="card-text "><small class="text-muted">
                    <i class="fas fa-star">{{article.calculateRating| floatformat:1}}</i>
                    <i class="fas fa-eye">      {{article.numViews}}</i>  <i class="fas fa-thumbs-up">{{article.numLikes}}</i>
                    <i class="far fa-user">  {{article.author.user.username}}</i>   <i class="fas fa-calendar-alt">   {{article.date_created|date:"M d, Y"}}</i></small></p>
                    <div style="display:flex">
                      {% for tag in article.tags.all %}
                      <a href="{% url 'revapp:tagged' tag.slug %}" class="mr-1 badge badge-info">#{{ tag }}</a>
                      {% endfor %}
                  </div>
              </div>
          </a>
      </div>  
      {%endfor%}    
      
  </div>


  {% if articles.has_other_pages %}
  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      {% if articles.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ articles.previous_page_number }}">&laquo;</a></li>
      {% else %}
        <li class="page-item"><span>&laquo;</span></li>
      {% endif %}
      {% for i in articles.paginator.page_range %}
        {% if articles.number == i %}
          <li class="active page-item"><span>{{ i }} <span class="sr-only"></span></span></li>
        {% else %}  
          <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
      {% endfor %}
      {% if articles.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ articles.next_page_number }}">&raquo;</a></li>
      {% else %}
        <li class="page-item"><span>&raquo;</span></li>
      {% endif %}
    </ul>
  </nav>
  {% endif %}
{%endblock%}

course work/kinovik/revapp/templates/revapp/article_update.html
{%extends 'home.html'%}
{%load crispy_forms_tags%}
{%load i18n%}
{% block content %}

<div class="container w-50  ">
  <font color="white">
  <form action="{%url 'revapp:update' article.slug%}" method="POST" enctype="multipart/form-data">
      {%csrf_token%}
      {{form.media}}
      <div class="form-row">
        <div class="form-group col-md-6 mb-0">
          {{ form.title|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
          {{ form.group|as_crispy_field }}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6 mb-0">

          {{ form.body|as_crispy_field }}
        </div>  
    </div>
    <div class="form-row">
        <div class="form-group  col-md-6 mb-0 ">
          {{form.rating|as_crispy_field}}
        </div>
        <div class="form-group col-md-6 mb-0">
          <div class="form-group  mb-0">
            <label>{% trans 'Tags'%}</label>
            <input type="text" data-role="tagsinput" class="form-control" name="tags">         
          </div>
        </div>
    </div>
        
      <button class="btn btn-primary btn-block" type="submit">{%trans 'EDIT'%}   <i class="fas fa-edit"></i></button>

</font>
</div>
    
{% endblock %}

course work/kinovik/revapp/templates/revapp/my_article.html
{%extends 'home.html'%}
{%load crispy_forms_tags%}
{%load i18n%}
{%block content%}
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container">
<div class="row flex-lg-nowrap">
  <div class="col">



    <div class="row flex-lg-nowrap">
      <div class="col mb-3">
        <div class="e-panel card">
          <div class="card-body">
            <div class="card-title">
              <h6 class="mr-2"><span></span><small class="px-1">{%trans 'Artcile manager'%}</small></h6>
            </div>
            <div class="e-table">
              <div class="table-responsive table-lg mt-3">
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      <th>{% trans 'Photo'%}</th>
                      <th class="max-width">{%trans 'Title'%}</th>
                      <th class="sortable">{%trans 'Date'%}</th>
                      <th>{%trans 'Actions'%}</th>
                    </tr>
                  </thead>
                  <tbody>
                      {%for article in articles%}
                    <tr>
                      <td class="align-middle text-center">
                       <a href="{%url 'revapp:detail' article.slug%}"><img class="card-img-top" src="{{article.images.first.image.url}}"> </a>
                      </td>
                     <td class="text-nowrap align-middle"> <a href="{%url 'revapp:detail' article.slug%}">{{article.title}}</a></td>
                      <td class="text-nowrap align-middle"><span>{{article.date_created|date:"M d, Y"}}</span></td>
                      <td class="text-center align-middle">
                        <div class="btn-group align-top">
                            <a href="{%url 'revapp:update' article.slug%}" class="btn btn-sm btn-outline-secondary badge" type="button" >{%trans 'Edit'%}</a>
                            <a href="{%url 'revapp:delete' article.slug%}" class="btn btn-sm btn-outline-secondary badge" type="button"><i class="fa fa-trash"></i></a>
                        </div>
                      </td>
                    </tr>
                    
                    {%endfor%}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-12 col-lg-3 mb-3">
       <table class="table">
           <thead>
               <div class="card">
                   <div class="card-title">
                    <h6 class="mr-2">{% trans 'Filter'%}</h6>
                    <ul class="nav nav-tabs">
                        
                        <form class="d-flex justify-content-center align-middle" method="GET">
                            {{filter.form|crispy}}

                            <li class="nav-item"><a class="nav-link active"><button class="btn btn-light"  type="submit"><i class="fas fa-search"></i></button></a></li>
                        </form>
                      </ul>
                   </div>
               </div>
           </thead>
           <tbody>
               <tr>
                <a href="{%url 'revapp:create'%}" class="btn btn-success btn-block">{%trans 'NEW ARICLE'%}<i class="fas fa-plus"></i></a>
               </tr>
           </tbody>
       </table>
      </div>
    </div>
    
  </div>
</div>
</div>
{%endblock%}

course work/kinovik/revapp/templates/revapp/upload.html
{%extends 'home.html'%}
{% load cloudinary%}




{% block content %}
<button id="upload_widget" class="cloudinary-button">Upload files</button>

<script src="https://widget.cloudinary.com/v2.0/global/all.js" type="text/javascript"></script>  

<script type="text/javascript">  

    var myWidget = cloudinary.createUploadWidget({
        cloudName: 'cloud_name',
        upload_preset: 'preset1',
        }, (error, result) => { if (result.event == "success") {
            console.log(result.info) // result.info contains data from upload
        } })

        document.getElementById("upload_widget").addEventListener("click", function(){
            myWidget.open();
        }, false);

</script>
{% endblock %}