course work/kinovik/kinovik/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls), 
    path('i18n/', include('django.conf.urls.i18n')),
    
]

urlpatterns += i18n_patterns(
    path('accounts/',include('allauth.urls')),
    path('', include('revapp.urls')),
)

course work/kinovik/revapp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'revapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.searchArticle, name='search'),
    path('group/', views.groupArticle, name='group'),
    path('create/', views.createArticle, name='create'),
    path('rate-article/', views.rateArticle, name='ratearticle'),
    path('my-articles/', views.myArticles, name='myarticles'),
    path('tag/<slug:slug>/', views.tagged, name='tagged'),
    path('<slug:slug>/like', views.likeUnlikeArticle, name='likeunlike'),
    path('<slug:slug>/detail', views.detailArticle, name='detail'),
    path('<slug:slug>/album', views.otherImages, name='otherimages'),
    path('<slug:slug>/update', views.updateArticle, name="update"),
    path('<slug:slug>/delete', views.deleteArticle, name='delete'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course work/kinovik/templates/home.html
{%load static%}
{% load cloudinary %}    
{% load socialaccount%} 
{% load i18n%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/png" href="https://res.cloudinary.com/djpkuwaix/image/upload/v1638582300/fav_yr4qo2.ico"/>
    <link href="/static/css/bootstrap.min.css"rel="stylesheet" type="text/css"> 
    <link href="{% static 'fontawesome_free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{%static 'css/style.css'%}"/>
    <link rel="stylesheet" href="{%static 'css/tagsinput.css'%}" />
    <title>993-7</title>
</head>
<body>  
  <header>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-dark nav-color py-3 ml-lg-5">    
        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="navbar-brand" href="{%url 'revapp:index'%}"> <span style="color:#17a2b8"><i class="fas fa-home fa-2x"></i></span></a>
              </li>
              <li class="nav-item">
                <form class="d-flex justify-content-center align-middle" action="{%url 'revapp:search'%}" method="GET">
                  <input class="form-control me-2" type="search" aria-label="Search" name="q">
                  <button class="btn btn-outline-info" type="submit">{% trans 'Search'%}</button>
                </form>
              </li>
            </ul>
            <div class="ms-auto">
              <form class="form-inline p-2" action="{% url 'set_language' %}" method="post">
                {% csrf_token %}
                <input name="next" type="hidden" value="{{ redirect_to }}">
                <select  class="form-control" name="language">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% for language in languages %}
                        <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %}
                                selected{% endif %}>
                             {{ language.code }}
                        </option>
                    {% endfor %}
                </select>
                <input  class="btn btn-outline-light" type="submit" value="Go">
            </form>
            </div>
            {% if user.is_authenticated %}
            <div class="dropdown ms-auto">
              <div class="dropdown-toggle " id="dropdownMenuButton"
              data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span style="color:#17a2b8"><i class="fas fa-users fa-2x"></i></span>
              </div>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                <div class="dropdown-item-text r">
                    <img src="/static/images/user.jpg" width="50" alt="User" class="rounded"/>                    
                    <p><span class="badge badge-secondary">{% trans 'Welcome'%},{{user.username}}</span></p>
                </div>                   
                <a class="dropdown-item btn btn-dark" href="{%url 'revapp:myarticles'%}">{% trans 'My articles' %}</a>
                <a class="dropdown-item" href="/accounts/logout">{% trans 'Log out'%}</a>   
              

              </div>      
            </div>
            {%else%}
            <a href="/accounts/login" type="button" class="btn btn-dark">{%trans 'Sign in'%}</a>
            <a href="/accounts/signup" type="button" class="btn btn-outline-info ">{%trans 'Sign up'%}</a>
            {%endif%}
        </div>         
      </nav>      
    </div>
</header>
<div class="main">
          <div class="row row-one mr-0">
            <div class ="col-1-4">
              <form class="d-flex justify-content-center align-middle" action="{%url 'revapp:group'%}" method="GET">
              <div class="d-inline btn-group-vertical " role="group" aria-label="Vertical button group">
                <button class="btn btn-secondary btn-lg " type="submit" id="button1" value="Home" name="group">{% trans 'Home'%}</button>
                <button class="btn btn-secondary btn-lg " type="submit" id="button1" value="Movie" name="group">{% trans 'Movie'%}</button>
                <button class="btn btn-secondary btn-lg " type="submit" id="button2" value="Books" name="group">{%trans 'Books'%}</button>
                <button class="btn btn-secondary btn-lg" type="submit" id="button3" value="Games" name="group"> {%trans 'Games'%}</button>
                
              </div>
              </form> 
              <div id="tagcloud">
                <ul>

              {%for tag in tags%}
                  <li><a class="ahref" href="{%url 'revapp:tagged' tag.slug%}"> {{tag.name}}</a></li>
              {%endfor%}
            </ul>
            </div>
            </div>
            <div class="col-3-4">
                {%block content%}
                {%endblock%}
            </div>
        </div>
</div>
<script src="{%static 'js/jquery.min.js'%}"></script>
<script src="{%static 'js/bootstrap.bundle.min.js'%}"></script>
<script src="/static/js/tagsinput.js"></script>
<script src="/static/js/tagcloud.jquery.js"></script>
<script src="/static/js/tagcloud.js"></script>
{%block extra_body%}
{%endblock%}